### ISSUE TITLE
Months wise experience 

### ISSUE THREAD

**Issue by lkmSasanga** [dilumn/peggedplacetowork#43]
Most of the newbies are getting new jobs after 6 months of the internship so they have 6 months of experience. Good to have 6 months in experience years dropdown. Like 0.5 years or something like that.

**Comment by dilumn** [comment]
Does the internship experience count as part of the experience? Because 0 experience is for fresh graduates, which means even though they have done previous internships while studying usually industry experience count start after graduation. I think internship is considered as a training period rather than experience

**Comment by lkmSasanga** [comment]
Yeah, I think you are right! Also, your project idea is very helpful. Thanks!
